# Getting Started with NumPy

In this notebook, we are going to perform some basic numpy operations. 

## What is a NumPy array?

According to NumPy documentation, an array "is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways".

## Hands-On

**Installing NumPy**

In case that NumPy is not yet installed in your system, run the following line of code.

In [1]:
!pip install numpy

Once the library has been properly installed, we can import it to our environment. It is highly recommended to follow the following convention:

In [2]:
import numpy as np

**Create a simple 1D array**

The following functions are examples on how to create basic 1D arrays. 

In [3]:
# Simple array from range: The function returns a numpy array with values from 0 to the specified index, non-inclusive.
simple_array = np.arange(6)
simple_array

array([0, 1, 2, 3, 4, 5])

In [4]:
# Random array: The function returns a numpy array with the specified shape filled with random float values between 0 and 1.
random_array = np.random.rand(10)
random_array

array([0.37725604, 0.60447049, 0.49823423, 0.08601617, 0.43911638,
       0.9804707 , 0.38454809, 0.04451509, 0.59271706, 0.64948836])

In [5]:
# Array from list: The function transforms a python list into a numpy array.
list_a = [2,4,6]
array_a = np.array(list_a)
array_a

array([2, 4, 6])

In [6]:
# We can also do the inverse task: transform an array into a list
array_a.tolist()

[2, 4, 6]

In [7]:
# We can execute previous function directly
array_b = np.array([1,3,5])
array_b

array([1, 3, 5])

In [8]:
# An array of 0's: The function returns an array with X number of 0's
zeros_array = np.zeros(5)
zeros_array

array([0., 0., 0., 0., 0.])

In [9]:
# Full custom array: The function returns an array full of our specified value. In this example, we are using the boolean True.
full_array = np.full((5),True)
full_array

array([ True,  True,  True,  True,  True])

**Exploring Arrays**

In [10]:
# We can check the number of elements in an array
print(f"Our random array has {len(random_array)} elements")
print(f"Our zeros array has {len(zeros_array)} elements")

Our random array has 10 elements
Our zeros array has 5 elements


In [11]:
# We can also check the size of the array in bites
print(f"The size of our random array is {random_array.itemsize}")

The size of our random array is 8


In [12]:
# Similar to lists, we can access values by index
random_array[5] #6th element of the random_array

0.9804707025025707

**Create Simple 2D Arrays**

Most of the functions we explored earlier are not limited to the creation of 1D arrays. In fact, the first argument of most of those functions is the shape of our array. Therefore, we can use this argument to create custom shape arrays. Let's create some 2D arrays. 

There are many other functions you can explore to create arrays accoding to what you need. Take a look at the following link and explore some of these functions:

https://numpy.org/doc/stable/reference/routines.array-creation.html

### Sources

* https://numpy.org/doc/stable/user/absolute_beginners.html