# Getting Started with NumPy - Module 2

In the previous module, we explored some basic transformations like slicing and returning arrays based on conditions. In this module, we are going to explore deeper by performing algebra functions to our arrays, as well as to explore how to perform linear algebra operations. By the end of this courselet you will be able to:

* Learn how transformations
* Use functions to perform operations and transform arrays
* Perform linear algebra operations on arrays

## Array Operations

In [1]:
import numpy as np

In [17]:
# Let's first create a couple of simple arrays to start working on
a = np.arange(10)
b = np.arange(-5,5)
twoD_a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
twoD_b = np.full((3,3),2)
print(f"Array a: {a}")
print(f"Array b: {b}")
print(f"Array twoD_a:\n {twoD_a}")
print(f"Array twoD_b:\n {twoD_b}")

Array a: [0 1 2 3 4 5 6 7 8 9]
Array b: [-5 -4 -3 -2 -1  0  1  2  3  4]
Array twoD_a:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array twoD_b:
 [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [20]:
# Simple operations in one array
print(a+3) # Addition of a value to all the elements of an array
print(a*2) # Multiplication to all elements of an array
print(a%2) # Return the residual of each element after dividing by 2
# Simple operations in twoD array
print("\n")
print(twoD_a+3) # Addition of a value to all the elements of an array
print(twoD_a*2) # Multiplication to all elements of an array
print(twoD_a%2) # Return the residual of each element after dividing by 2

[ 3  4  5  6  7  8  9 10 11 12]
[ 0  2  4  6  8 10 12 14 16 18]
[0 1 0 1 0 1 0 1 0 1]


[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]]


## Linear Algebra

In [29]:
matrix_1 = np.arange(12)
matrix_1.resize(3,4)
print(matrix_1)
matrix_2 = np.arange()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In a conventional NumPy multiplication, we could perform the following operation.