# Getting Started with NumPy

In this notebook, we are going to perform some basic numpy operations. 

## What is a NumPy array?

According to NumPy documentation, an array "is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways".

## Hands-On

**Installing NumPy**

In case that NumPy is not yet installed in your system, run the following line of code.

In [1]:
!pip install numpy

Once the library has been properly installed, we can import it to our environment. It is highly recommended to follow the following convention:

In [2]:
import numpy as np

**Create a simple 1D array**

The following functions are examples on how to create basic 1D arrays. 

In [19]:
# Array from list: The function transforms a python list into a numpy array.
list_a = [2,4,6]
array_a = np.array(list_a)
array_a

array([2, 4, 6])

In [20]:
# We can also do the inverse task: transform an array into a list
array_a.tolist()

[2, 4, 6]

In [3]:
# Simple array from range: The function returns a numpy array with values from 0 to the specified index, non-inclusive.
simple_array = np.arange(6)
simple_array

array([0, 1, 2, 3, 4, 5])

In [29]:
# Random array: The function returns a numpy array with the specified shape filled with random float values between 0 and 1.
random_array = np.random.rand(10)
random_array

array([0.56627122, 0.31912986, 0.30376344, 0.27510398, 0.50278722,
       0.53872884, 0.29581828, 0.86580471, 0.3548771 , 0.45904333])

In [6]:
# We can also do the inverse task: transform an array into a list
array_a.tolist()

[2, 4, 6]

In [8]:
# An array of 0's: The function returns an array with X number of 0's
zeros_array = np.zeros(5)
zeros_array

array([0., 0., 0., 0., 0.])

In [9]:
# Full custom array: The function returns an array full of our specified value. In this example, we are using the boolean True.
full_array = np.full((5),True)
full_array

array([ True,  True,  True,  True,  True])

**Exploring Arrays**

In [10]:
# We can check the number of elements in an array
print(f"Our random array has {len(random_array)} elements")
print(f"Our zeros array has {len(zeros_array)} elements")

Our random array has 10 elements
Our zeros array has 5 elements


In [11]:
# We can also check the size of the array in bites
print(f"The size of our random array is {random_array.itemsize}")

The size of our random array is 8


In [12]:
# Similar to lists, we can access values by index
random_array[5] #6th element of the random_array

0.022479509731078928

**Create Simple 2D Arrays**

Most of the functions we explored earlier are not limited to the creation of 1D arrays. We can customize the shape of our arrays according to the type of data we are working with. Let's create some 2D arrays. 

In [25]:
#2D Array from list - From a list of lists, we are creating an array of arrays (that's what makes it 2D)
twoD_array = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
twoD_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
# We can confirm the dimensions
twoD_array.ndim

2

In [27]:
# We can also call elements in our array by index
twoD_array[2][3]

12

In [22]:
# Random 2D Array
random_2Darray = np.random.rand(10,2)
random_2Darray

array([[0.56440639, 0.83857345],
       [0.30522708, 0.19613412],
       [0.92490772, 0.33439001],
       [0.85939502, 0.10427667],
       [0.09577342, 0.76846047],
       [0.280186  , 0.45474868],
       [0.46008758, 0.24471278],
       [0.29853466, 0.03819388],
       [0.973254  , 0.31599518],
       [0.31712666, 0.675755  ]])

In [24]:
#Full custom 2D Array
full_2Darray = np.full((5,3),"NumPy is Awasome!")
full_2Darray

array([['NumPy is Awasome!', 'NumPy is Awasome!', 'NumPy is Awasome!'],
       ['NumPy is Awasome!', 'NumPy is Awasome!', 'NumPy is Awasome!'],
       ['NumPy is Awasome!', 'NumPy is Awasome!', 'NumPy is Awasome!'],
       ['NumPy is Awasome!', 'NumPy is Awasome!', 'NumPy is Awasome!'],
       ['NumPy is Awasome!', 'NumPy is Awasome!', 'NumPy is Awasome!']],
      dtype='<U17')

## Discover more

There are many other functions you can explore to create arrays accoding to what you need. Take a look at the following link and explore some of these functions:

https://numpy.org/doc/stable/reference/routines.array-creation.html

## Hands-on

Now it is your turn to create some arrays by your own. Some of the tasks require you to explore some functions not covered in this module.

In [ ]:
# Task 1 - Create 2D array of random values between 0 and 1


In [ ]:
# Task 2 - Create a simple 1D array with 12 random integers


In [ ]:
# Task 3 - Create a simple 3D array from a list


In [ ]:
# Task 4 - Create a 4D array full of zeros 
