# Getting Started with NumPy - Module 2

In the previous module, we explored some basic transformations like slicing and returning arrays based on conditions. In this module, we are going to explore deeper by performing algebra functions to our arrays, as well as to explore how to perform linear algebra operations. By the end of this courselet you will be able to:

* Learn how different transformations affect our arrays
* Use functions to perform operations and transform arrays
* Perform linear algebra operations on arrays

In [2]:
import numpy as np

In [3]:
# Let's first create a couple of simple arrays to start working on
a = np.arange(10)
b = np.arange(-5,5)
twoD_a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
twoD_b = np.full((3,3),2)
print(f"Array a: {a}\n")
print(f"Array b: {b}\n")
print(f"Array twoD_a:\n {twoD_a}\n")
print(f"Array twoD_b:\n {twoD_b}\n")

Array a: [0 1 2 3 4 5 6 7 8 9]

Array b: [-5 -4 -3 -2 -1  0  1  2  3  4]

Array twoD_a:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array twoD_b:
 [[2 2 2]
 [2 2 2]
 [2 2 2]]



## Basic Operations

Basic operations on Numpy Arrays are elementwise. This means that our operations affect one element of the array at a time. Let's take a brief look at some examples.

- Adding a value to all the elements of an array

In [3]:
a+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

- Multiplying all elements of an array by the same factor

In [4]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:


print(a%2) # Return the residual of each element after dividing by 2
# Simple operations in twoD array
print("\n")
print(twoD_a+3) # Addition of a value to all the elements of an array
print(twoD_a*2) # Multiplication to all elements of an array
print(twoD_a%2) # Return the residual of each element after dividing by 2

[0 1 0 1 0 1 0 1 0 1]


[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]]


## Unary Functions

Another common type of operations we can perform on our arrays is the use of pre-defined unary functions, which are also elementwise. Let's look a few examples.

- Square Root

In [6]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

- Exponential Function

In [7]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

- Logarithmic

In [8]:
np.log(a[1:]) # We are omitting the application of the function to the first value as this is not mathematically correct

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Reduction Operations

We can also perform operations that reduce the number of elements in our array. Let's take a look to a few.

- Sum of the elements of an array

In [9]:
np.sum(a)

45

- Max value of an array

In [10]:
np.max(a)

9

- Mean of the values of an array

In [11]:
np.mean(a)

4.5

Previous examples only cover the case of 1D arrays returning a single value. In the case of multiple dimensional arrays, we can provide more specifications to our functions to return different results. Let's take a look at this with the **sum** function. 

- Sum of the elements of an array (as previously explored)

In [12]:
np.sum(twoD_a) # We sum all the values

78

- Sum of the elements of an array, "column" wise

In [13]:
np.sum(twoD_a, axis=0) # Each value corresponds to the sum of each "column"

array([15, 18, 21, 24])

- Sum of the elements of an array, "row" wise

In [14]:
np.sum(twoD_a, axis=1) # Each value corresponds to the sum of each "row"

array([10, 26, 42])

To take a deeper look into the full collection of mathematical operations, you can explore the [source documentation](https://numpy.org/doc/stable/reference/routines.math.html)

## Logic Operations

Another common task is to perform logical operations on NumPy arrays and return an array of booleans with the result of each evaluation.

- Elements equal to one value

In [8]:
a==0

array([ True, False, False, False, False, False, False, False, False,
       False])

- Elements greater than one value

In [7]:
a>0

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## Linear Algebra

Some of you might have already notice the potential to threat NumPy arrays as vectors and matrices for multiple modeling applications. NumPy possess a series of functions which allows us to perform multiple linear algebra operations. Let's explore some examples in the following cells. You're always invited to discover more functions by exploring the [source documentation](https://numpy.org/doc/stable/reference/routines.linalg.html#module-numpy.linalg).

### Vector operations

Let's explore some basic vector operations.

- [Dot Product](https://en.wikipedia.org/wiki/Dot_product)

In [15]:
np.dot(a,b)

60

- [Outer Product](https://en.wikipedia.org/wiki/Outer_product)

In [16]:
np.outer(a,b)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4],
       [-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8],
       [-15, -12,  -9,  -6,  -3,   0,   3,   6,   9,  12],
       [-20, -16, -12,  -8,  -4,   0,   4,   8,  12,  16],
       [-25, -20, -15, -10,  -5,   0,   5,  10,  15,  20],
       [-30, -24, -18, -12,  -6,   0,   6,  12,  18,  24],
       [-35, -28, -21, -14,  -7,   0,   7,  14,  21,  28],
       [-40, -32, -24, -16,  -8,   0,   8,  16,  24,  32],
       [-45, -36, -27, -18,  -9,   0,   9,  18,  27,  36]])

In [17]:
# Inner product
np.inner(a,b)

60

### Matrix operations

Now, let's take a look at some recurrent matrix operations.

In a conventional NumPy multiplication, we can perform a multiplication in which each element is multiplied the corresponding element based on index. We can see that in the following cell:

In [18]:
matrix_1 = np.arange(12)
matrix_1.resize(3,4) # Using the resize method directly applies the transformation to our matrix
print(matrix_1)
matrix_2 = np.arange(12,24).reshape(3,4) # Or we can apply reshape directly
print(matrix_2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [19]:
# Conventional array multiplication
matrix_1*matrix_2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

However, this type of multiplication doesn't follow the rules of linear algebra. To perform a proper matrix multiplication, we must use the *matmul* function.

In [20]:
# Matrix multiplication
np.matmul(matrix_1,matrix_2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

As you can see, we are getting an error. This is because the number of rows of columns of the first matrix is not equal to the number of rows of the second matrix, a fundamental rule of matrix multiplication. Let's reshape our matrix to perform matrix multiplication.

In [21]:
# Matrix multiplication
matrix_3 = np.reshape(matrix_1,(4,3))
np.matmul(matrix_3,matrix_2)

array([[ 56,  59,  62,  65],
       [200, 212, 224, 236],
       [344, 365, 386, 407],
       [488, 518, 548, 578]])

An opperation that we can actually perform with our original two matrices, is to calculate the [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product):

In [22]:
# Kronecker product
np.kron(matrix_1,matrix_2)

array([[  0,   0,   0,   0,  12,  13,  14,  15,  24,  26,  28,  30,  36,
         39,  42,  45],
       [  0,   0,   0,   0,  16,  17,  18,  19,  32,  34,  36,  38,  48,
         51,  54,  57],
       [  0,   0,   0,   0,  20,  21,  22,  23,  40,  42,  44,  46,  60,
         63,  66,  69],
       [ 48,  52,  56,  60,  60,  65,  70,  75,  72,  78,  84,  90,  84,
         91,  98, 105],
       [ 64,  68,  72,  76,  80,  85,  90,  95,  96, 102, 108, 114, 112,
        119, 126, 133],
       [ 80,  84,  88,  92, 100, 105, 110, 115, 120, 126, 132, 138, 140,
        147, 154, 161],
       [ 96, 104, 112, 120, 108, 117, 126, 135, 120, 130, 140, 150, 132,
        143, 154, 165],
       [128, 136, 144, 152, 144, 153, 162, 171, 160, 170, 180, 190, 176,
        187, 198, 209],
       [160, 168, 176, 184, 180, 189, 198, 207, 200, 210, 220, 230, 220,
        231, 242, 253]])

In [23]:
# Determinant of a matrix
squared_matrix = np.array([[2,2],[5,-1]])
np.linalg.det(squared_matrix)

-11.999999999999995

In [24]:
# Rank of a matrix
np.linalg.matrix_rank(squared_matrix)

2

In [25]:
# Eigen values and eigen vectors - squared matrix
eigen_result = np.linalg.eig(squared_matrix)
print(f"The eigen values of our squared matrix are {eigen_result[0]}")
print(f"The eigen vectors of our squared matrix are {eigen_result[1]}")

The eigen values of our squared matrix are [ 4. -3.]
The eigen vectors of our squared matrix are [[ 0.70710678 -0.37139068]
 [ 0.70710678  0.92847669]]


In [26]:
# Inverse of a matrix
np.linalg.inv(squared_matrix)

array([[ 0.08333333,  0.16666667],
       [ 0.41666667, -0.16666667]])

In [27]:
# Transpose of a matrix
squared_matrix.T

array([[ 2,  5],
       [ 2, -1]])

### Solving linear equations

We can now leverage what we have learned so far and use NumPy to solve a system of linear equations.

Let's say we have the following system of equations: 
$$
2x_1+3x_2=19
$$
$$
x_1+x_2=7
$$
We can define our system in NumPy as a combination of a matrix containing the coefficients values, and one vector with our results values. Then, we can compute the values of $x_1$ and $x_2$ through the *linalg.solve* function.

In [28]:
coeff = np.array([[2,3],[1,1]])
r = np.array([19,7])
x_vector = np.linalg.solve(coeff,r)
x_vector

array([2., 5.])

Our function solved that $x_1=2$ and $x_2=5$. We can verify our results computing the dot product between our x's vector and the coefficients matrix, and comparing the resulting vector with our results vector.

In [29]:
np.allclose(np.dot(coeff,x_vector),r)

True

Our results are correct!

## Hands-on

In [ ]:
# Task 1 - Create 2 6-elements vectors full of random values between 0 and 1 and calculate their dot product


In [ ]:
# Task 2 - Solve the following system of equations and check that your result is correct using np.allclose
"""
3*x1+4*x2+2*x3 = 47
6*x1-4*x2+1*x3 = 31
1*x1+1*x2-1*x3 = 6
"""
