# Getting Started with NumPy - Module 1

In this notebook, we are going to explore the main NumPy object, the NumPy array. By the end of this courselet you will be able to:

* Identify what is a NumPy array
* Create array using multiple methods and functions, according to the type of array that you need.
* Create arrays of multiple dimensions

## What is a NumPy array?

According to NumPy documentation, an array "is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways".

**Installing NumPy**

In case that NumPy is not yet installed in your system, run the following line of code.

In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: C:\Users\pramonettivega\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Once the library has been properly installed, we can import it to our environment. It is highly recommended to follow the following convention:

In [2]:
import numpy as np

**Create a simple 1D array**

The following functions are examples on how to create basic 1D arrays. 

In [3]:
# Array from list: The function transforms a python list into a numpy array.
list_a = [2,4,6]
array_a = np.array(list_a)
array_a

array([2, 4, 6])

In [4]:
# We can also do the inverse task: transform an array into a list
array_a.tolist()

[2, 4, 6]

In [5]:
# Simple array from range: The function returns a numpy array with values from 0 to the specified index, non-inclusive.
simple_array = np.arange(10)
simple_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Random array: The function returns a numpy array with the specified shape filled with random float values between 0 and 1.
random_array = np.random.rand(10)
random_array

array([0.73254704, 0.21540049, 0.28138281, 0.02377387, 0.88921113,
       0.20992418, 0.68287898, 0.2065392 , 0.43782254, 0.47510816])

In [7]:
# We can also do the inverse task: transform an array into a list
array_a.tolist()

[2, 4, 6]

In [8]:
# An array of 0's: The function returns an array with X number of 0's
zeros_array = np.zeros(5)
zeros_array

array([0., 0., 0., 0., 0.])

In [9]:
# Full custom array: The function returns an array where all of the elements correspond to the same object of the same data type. 
# In this example, we are using the boolean True.
full_array = np.full((5),True)
full_array

array([ True,  True,  True,  True,  True])

**Exploring Arrays, Indexing and Slicing**

In [10]:
# We can check the number of elements in an array
print(f"Our random array has {len(random_array)} elements")
print(f"Our zeros array has {len(zeros_array)} elements")

Our random array has 10 elements
Our zeros array has 5 elements


In [11]:
# We can also check the size of the array in bites
print(f"The size of our random array is {random_array.itemsize}")

The size of our random array is 8


In [12]:
# Similar to lists, we can access values by index
simple_array[5] #6th element of the random_array

5

In [13]:
# Also similar to lists, we can slice our array. For example, from indexes 1 to 4
simple_array[1:4]

array([1, 2, 3])

In [14]:
# We can also define steps [start:end:step]
simple_array[1:8:2]

array([1, 3, 5, 7])

In [15]:
# Reverse our array
simple_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
# Reverse AND slice our array. As you will observe in the output, the array is first reversed, 
# and then the slicing is performed over the reversed array
simple_array[::-1][1:8:2]

array([8, 6, 4, 2])

In [17]:
# An interesting feature of the arrays is the possibility to slice them based on a condition. For example, let's use our random array and
# return an array with the elements higher than 0.5
random_array[random_array>0.5]

array([0.73254704, 0.88921113, 0.68287898])

You're invited to explore more techniques to index your and explore arrays.

**Create Simple 2D Arrays**

Most of the functions we explored earlier are not limited to the creation of 1D arrays. We can customize the shape of our arrays according to the type of data we are working with. Let's create some 2D arrays. 

In [18]:
#2D Array from list - From a list of lists, we are creating an array of arrays (that's what makes it 2D)
twoD_array = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
twoD_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
# We can confirm the dimensions
twoD_array.ndim

2

In [20]:
# We can also call elements in our array by index
twoD_array[2][3]

12

In [21]:
# Random 2D Array
random_2Darray = np.random.rand(10,2)
random_2Darray

array([[5.18360593e-02, 2.21044456e-01],
       [8.29763893e-01, 5.40873252e-02],
       [3.20079834e-01, 1.70482344e-01],
       [7.63429430e-01, 4.11590081e-01],
       [1.30387225e-01, 8.14446888e-01],
       [3.94986575e-01, 4.88475012e-02],
       [4.96407625e-01, 2.59590488e-01],
       [5.39122572e-01, 3.27130343e-01],
       [2.73545121e-03, 3.37708262e-01],
       [7.07669744e-01, 6.68936924e-04]])

In [22]:
#Full custom 2D Array
full_2Darray = np.full((5,3),"Hello World!")
full_2Darray

array([['Hello World!', 'Hello World!', 'Hello World!'],
       ['Hello World!', 'Hello World!', 'Hello World!'],
       ['Hello World!', 'Hello World!', 'Hello World!'],
       ['Hello World!', 'Hello World!', 'Hello World!'],
       ['Hello World!', 'Hello World!', 'Hello World!']], dtype='<U12')

**Exploring Arrays, Indexing and Slicing**

In [23]:
# Accesing and individual element. In this example, element 2,1 from our twoD_array.
twoD_array[2,1] # We are first accesing the row index 2 of the main array [9,10,11,12], and then accesing the element index 1 [10]

10

In [24]:
# We can also slice rows. For example, here we slice the first two rows
twoD_array[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
# All rows and 2nd,3rd column
twoD_array[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## Discover more

There are many other functions you can explore to create arrays accoding to what you need. Take a look at the following link and explore some of these functions:

[NumPy Documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html)

## Hands-on

Now it is your turn to create some arrays by your own. Some of the tasks require you to explore some functions not covered in this module.

In [26]:
# Task 1 - Create 2D array of random values between 0 and 1


In [27]:
# Task 2 - Create a simple 1D array with 12 random integers


In [28]:
# Task 3 - Create a simple 3D array from a list


In [29]:
# Task 4 - Create a 4D array full of zeros 


In [30]:
# Task 5 - Return the second and third columns of a 4x5 2D array
